language: python
before_install:
  - sudo apt-get update
  - sudo apt-get -y install graphviz
python:
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - python setup.py pytest